### ISSUE TITLE
cannot compile the php-extension

### ISSUE THREAD

**Issue by karl-xiao** [shooyaaa/php_bitmap#1]
i want to know which version of php you use;

and i configure it with my local php5.6.21 that find some error.

like that:
php_bitmap-master/bitmap.c:73:20: error: no member named
      'handlers' in 'struct _zend_object'
    intern->object.handlers = &bitmap_handlers;

php_bitmap-master/bitmap.c:134:30: error: too few arguments
      provided to function-like macro invocation
    RETURN_STRINGL(&result, 1);

**Comment by shooyaaa** [comment]
At first, it only compiled under php7 , now php5 also works! please try again
